apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /opt/static
              name: media-volume
            - name: secret-volume
              mountPath: /usr/local/nginx/ssl
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: vod-live-ssl
        - name: media-volume
          persistentVolumeClaim:
            claimName: 'media-pvc'
