apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}02
  labels:
    app: {{ .Chart.Name }}02
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
